clock improved

diff --git a/checkfonts b/checkfonts
--- a/checkfonts
+++ b/checkfonts
@@ -39,22 +39,40 @@ if [ ! -e "${FONTDIR}Ubuntu-B.ttf" ]; then
 	ln -s "$font" "${FONTDIR}Ubuntu-B.ttf"
 fi
 
-printf "Checking for \"Courier New Fett\"..."
-font="$(fc-list :fullname='Courier New Fett' file)"
+printf "Checking for \"Ubuntu Mono Bold\"..."
+font="$(fc-list :fullname='Ubuntu Mono Bold' file)"
 font=$(splitfont "$font")
 if [ -z "$font" ]; then
 	printf " fail.\n"
-	printf "  \"Courier New Fett\" not found\n"
-	printf "  Debian/Ubuntu User run \"apt-get install ttf-mscorefonts-installer\"\n"
-	printf "  on other Systems go to \"http://corefonts.sourceforge.net/\"\n"
+	printf "  \"Ubuntu Mono Bold\" not found\n"
+	printf "  Ubuntu User run \"apt-get install ttf-ubuntu-font-family\"\n"
+	printf "  on other Systems go to \"http://font.ubuntu.com/\"\n"
 	exit 1
 else
 	printf " pass.\n"
 	printf "  found at \"$font\"\n"
 fi
-if [ ! -e "${FONTDIR}courbd.ttf" ]; then
-	printf "  linking \"${FONTDIR}courbd.ttf\" to \"$font\"\n"
-	ln -s "$font" "${FONTDIR}courbd.ttf"
+if [ ! -e "${FONTDIR}UbuntuMono-B.ttf" ]; then
+	printf "  linking \"${FONTDIR}UbuntuMono-B.ttf\" to \"$font\"\n"
+	ln -s "$font" "${FONTDIR}UbuntuMono-B.ttf"
+fi
+
+printf "Checking for \"Ubuntu Condensed\"..."
+font="$(fc-list :fullname='Ubuntu Condensed' file)"
+font=$(splitfont "$font")
+if [ -z "$font" ]; then
+	printf " fail.\n"
+	printf "  \"Ubuntu Condensed\" not found\n"
+	printf "  Ubuntu User run \"apt-get install ttf-ubuntu-font-family\"\n"
+	printf "  on other Systems go to \"http://font.ubuntu.com/\"\n"
+	exit 1
+else
+	printf " pass.\n"
+	printf "  found at \"$font\"\n"
+fi
+if [ ! -e "${FONTDIR}Ubuntu-C.ttf" ]; then
+	printf "  linking \"${FONTDIR}Ubuntu-C.ttf\" to \"$font\"\n"
+	ln -s "$font" "${FONTDIR}Ubuntu-C.ttf"
 fi
 
 printf "Checking for \"VDRSymbols Sans\"..."
